spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/webrise_db
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
        hbm2ddl.auto: none
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
